In [1]:
#numpy基于数组的算法比python 列表快10-100倍
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print("Numpy 耗时：")
%time for _ in range(10):my_arr2 = my_arr * 2
print("Python List 耗时：")
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Numpy 耗时：
CPU times: total: 46.9 ms
Wall time: 46.5 ms
Python List 耗时：
CPU times: total: 1.5 s
Wall time: 1.53 s


In [2]:
#4.1numpy ndarray
#创建数组  特点：同质性（元素必须是相同类型）
data2 = [[1,2,3,4],[5,6,7,8]] 
arr2 = np.array(data2)
print(f"数组内容:\n{arr2}")
print(f"维度 (ndim): {arr2.ndim}")
print(f"形状 (shape): {arr2.shape}")
print(f"类型 (dtype): {arr2.dtype}")

数组内容:
[[1 2 3 4]
 [5 6 7 8]]
维度 (ndim): 2
形状 (shape): (2, 4)
类型 (dtype): int64


In [3]:
#把8改成8.5 dtype的变化：
data2 = [[1,2,3,4],[5,6,7,8.5]] 
arr2 = np.array(data2)
print(f"数组内容:\n{arr2}")
print(f"维度 (ndim): {arr2.ndim}")
print(f"形状 (shape): {arr2.shape}")
print(f"类型 (dtype): {arr2.dtype}")

数组内容:
[[1.  2.  3.  4. ]
 [5.  6.  7.  8.5]]
维度 (ndim): 2
形状 (shape): (2, 4)
类型 (dtype): float64


In [7]:
#快速创建
print(np.zeros(10)) #zeros
print(np.ones((3,6)))
print(np.empty((2,3,2)))   #empty不一定都是0  2个3*2
print(np.arange)
#range 和 arange区别 前者是迭代器，需要用list()才能看到内容 后者是数组且支持向量化运算

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[1.30674021e-311 2.47032823e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.37961302e-306 5.64233733e-067]]

 [[7.42380062e-091 5.79795887e+170]
  [5.51292489e+169 1.80361313e+185]
  [3.99910963e+252 1.79454988e-052]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
#astype
arr = np.array([1,2,3,4,5])
print(f"原式类型：{arr.dtype}")
float_arr = arr.astype(np.float64)
print(f'新类型：{float_arr.dtype}')
print(f'新数组内容：{float_arr}')

原式类型：int64
新类型：float64
新数组内容：[1. 2. 3. 4. 5.]


In [14]:
#把字符串数字变真数字
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype='S')
converted_arr = numeric_strings.astype(float)
print(converted_arr)

[ 1.25 -9.6  42.  ]


In [15]:
#如果数组里有字符转成浮点数会发生？
num = np.array(['1.2','whoops'],dtype='S')
converted_num = num.astype(float)
print(converted_num)

ValueError: could not convert string to float: np.bytes_(b'whoops')

In [16]:
#数组计算
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr + arr)
print(1/arr)
#比较
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2 > arr)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[False  True False]
 [ True False  True]]
